apiVersion: apps/v1
kind: Deployment
metadata:
  name: rds
  namespace: oih-dev-ns
  labels:
    app: rds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rds
  template:
    metadata:
      labels:
        app: rds
    spec:
      containers:
      - name: rds
        image: openintegrationhub/rds:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: rds
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: rds
              key: "mongourl"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: rds
              key: "iamtoken"
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
