apiVersion: v1
kind: Service
metadata:
  name: rds
  namespace: oih-dev-ns
  labels:
    app: rds
spec:
  type: NodePort
  selector:
    app: rds
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
