globals:
  fetch: true
env:
  commonjs: true
  node: true
  jest: true
plugins:
- prettier
extends:
- airbnb-base
- plugin:prettier/recommended
rules:
  import/order: 0
  no-loop-func: 0
  no-plusplus: 0
  no-console: 'off'
  react/prop-types: 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
  no-underscore-dangle: 0
  no-param-reassign: 0
  no-continue: 0
  no-unsafe-finally: 0
  global-require: 0
  consistent-return: 0