apiVersion: apps/v1
kind: Deployment
metadata:
  name: ils
  namespace: oih-dev-ns
  labels:
    app: ils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ils
  template:
    metadata:
      labels:
        app: ils
    spec:
      containers:
      - name: ils
        image: openintegrationhub/ils:latest
        ports:
        - containerPort: 3003
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: ils
              key: "mongourl"
        - name: SCHEMA_TOKEN
          valueFrom:
            secretKeyRef:
              name: ils
              key: "iamtoken"
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3003
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3003
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
