apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  namespace: oih-dev-ns
  labels:
    app: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
      - name: dispatcher-service
        image: openintegrationhub/dispatcher-service:latest
        ports:
        - containerPort: 3013
        envFrom:
        - configMapRef:
            name: dispatcher-service
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: dispatcher-service
              key: "mongourl"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: dispatcher-service
              key: "iamtoken"
        - name: FLOW_TOKEN
          valueFrom:
            secretKeyRef:
              name: dispatcher-service
              key: "flowtoken"
        resources:
          limits:
            cpu: "0.1"
            memory: 1000Mi
        livenessProbe:
          httpGet:
            port: 3013
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3013
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
