apiVersion: v1
kind: Service
metadata:
  name: webhooks-service
  namespace: oih-dev-ns
  labels:
    app: webhooks-service
spec:
  type: NodePort
  selector:
    app: webhooks
  ports:
  - name: "1234"
    protocol: TCP
    port: 1234
    targetPort: 1234
