apiVersion: v1
kind: ConfigMap
metadata:
  name: rds
  namespace: oih-dev-ns
data:
  INTROSPECT_ENDPOINT_BASIC: "https://iam.openintegrationhub.com/api/v1/tokens/introspect"
  INTROSPECT_TYPE: basic
  NODE_ENV: production
  QUEUE_URL: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
  LOG_LEVEL: info
  CORS_ORIGIN_WHITELIST: openintegrationhub.com,https://web-ui.openintegrationhub.com