apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-log
  namespace: oih-dev-ns
  labels:
    app: audit-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-log
  template:
    metadata:
      labels:
        app: audit-log
    spec:
      containers:
      - name: audit-log
        image: openintegrationhub/audit-log:latest
        ports:
        - containerPort: 3007
        envFrom:
        - configMapRef:
            name: audit-log
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: audit-log
              key: "mongourl"
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: audit-log
              key: "iamtoken"
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3007
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3007
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: Always
