apiVersion: v1
kind: ConfigMap
metadata:
  name: component-repository
  namespace: oih-dev-ns
data:
  CORS_ORIGIN_WHITELIST: "openintegrationhub.com,http://web-ui.openintegrationhub.com"
  INTROSPECT_ENDPOINT_BASIC: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
  LOG_LEVEL: trace
  PORT: "1234"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local"
