apiVersion: v1
kind: Service
metadata:
  name: reports-analytics
  namespace: oih-dev-ns
  labels:
    app: reports-analytics
spec:
  type: NodePort
  selector:
    app: reports-analytics
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
