apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-log
  namespace: oih-dev-ns
data:
  EXCHANGE_NAME: audit-logs
  EXCHANGE_TOPIC: logs
  INTROSPECT_ENDPOINT_BASIC: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
  INTROSPECT_TYPE: basic
  QUEUE_URL: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
